---
- name: assures /usr/share/ansible/scripts dir exists
  file: path=/usr/share/ansible/scripts state=directory
- name: nic tuning  scripts
  copy: src="{{item}}" dest={{"/" + item}} mode=755
  with_items:
    - usr/share/ansible/scripts/nic_tuning.py
    - etc/network/if-up.d/ifup-local
  notify: execute nic_tuning script
