apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: {{hyperkube_image}}
    command:
    - /hyperkube
    - proxy
    - --hostname-override={{inventory_hostname}}
    - --cluster-cidr={{service_cidr}}
    - --kubeconfig=/etc/kubernetes/proxy-kubeconfig.yaml
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/kubernetes/proxy-kubeconfig.yaml
      name: proxy-kubeconfig
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /etc/kubernetes/proxy-kubeconfig.yaml
    name: proxy-kubeconfig
